CricketFantasy/CricketFantasy/Controllers/PlayersController.cs
using CricketFantasy.DataLayer;
using CricketFantasy.DataLayer.Model;
using CricketFantasy.DataTransferObjects.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CricketFantasy.Controllers
{
    public class PlayersController : Controller
    {
        // GET: Players
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult CreatePlayer(int PlayerId, int TeamId)
        {
            PlayersDto model = new PlayersDto();

            if (PlayerId != 0)       
            {
                var TeamInfo = DataAccess.Instance.PlayersActions.Get(PlayerId);
                model.TeamId = TeamId;
                model.PlayerName = TeamInfo.PlayerName;
             //   model.isCaptain = TeamInfo.IsCaptain;
                model.PlayerType = TeamInfo.PlayerType;

            }
            return PartialView(model);
        }


        [HttpPost]
        public ActionResult CreatePlayer(PlayersDto model)
        {

            if (model.PlayerId != 0)
            {
                var PlayerInfo = DataAccess.Instance.PlayersActions.Get(model.PlayerId);
                PlayerInfo.PlayerName = model.PlayerName;
              //  PlayerInfo.IsCaptain = model.isCaptain;
                PlayerInfo.PlayerType = model.PlayerType;
                DataAccess.Instance.PlayersActions.Change(PlayerInfo);
            }
            else
            {
                Player player = new Player();
//                player.team_Id = model.TeamId;
                player.PlayerName = model.PlayerName;
    //            player.IsCaptain = model.isCaptain;
  //            //  player.SystemUserId = "0";
                player.IsActive = true;
                player.PlayerType = model.PlayerType;
                DataAccess.Instance.PlayersActions.Add(player);
            }

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetPlayersData(int TeamId)
        {
           // int[] PlayersAssigned = DataAccess.Instance.TeamPlayerAction.GetAll().Where(x => x.TeamId != TeamId).Select(x => x.PlayerId).ToArray();
            List<PlayersDto> Players = DataAccess.Instance.PlayersActions.GetAll().AsEnumerable().Select(x => new PlayersDto {
                PlayerId = x.Id,
                PlayerName = x.PlayerName,
                PlayerType = x.PlayerType,
                IsInCurrentTeam = DataAccess.Instance.TeamPlayerAction.GetAll().Where(y=>y.TeamId == TeamId && y.PlayerId == x.Id).Any()
            }).ToList();
            return PartialView(Players);
        }
    }
}

CricketFantasy/CricketFantasy/Views/Players/CreatePlayer.cshtml
@model CricketFantasy.DataTransferObjects.Models.PlayersDto

@using (Ajax.BeginForm("CreatePlayer", "Players", new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "CreatePlayerSuccess",
    OnFailure = "CreatePlayerFailure",
}))
{
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PlayerId)
    @Html.HiddenFor(model => model.TeamId)
    <div class="form-group">
        @Html.Label("Player Name", htmlAttributes: new { @class = "control-label col-md-3 requiredfield" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.PlayerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlayerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Player Type", htmlAttributes: new { @class = "control-label col-md-3 requiredfield" })
        <div class="col-md-9">
            @Html.DropDownListFor(model => model.PlayerType,
           new SelectList(
                  new List<Object>{
                        new { value = "Batsman" , text = "Batsman" },
                       new { value = "Bowler", text = "Bowler"},
                       new { value = "Wicket Keeper", text = "Wicket Keeper"},
                       new { value = "All Rounder", text = "All Rounder"}
                    },
                  "value",
                  "text",
                   Model.PlayerType
           ), new { @class="form-control" })
            @Html.ValidationMessageFor(model => model.PlayerType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Is Captain", htmlAttributes: new { @class = "control-label col-md-3" })
        <div class="col-md-9">
           @Html.CheckBoxFor(model => model.isCaptain, new { htmlAttributes = new { @class = "form-control" } })
            
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
            <input type="submit" value="Create" id="CreatePlayerBtn" class="HideItem btn btn-default" />
        </div>
    </div>
</div>
}
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CricketFantasy/CricketFantasy/Views/Players/GetPlayersData.cshtml
@model IEnumerable<CricketFantasy.DataTransferObjects.Models.PlayersDto>

<table class="table table-striped table-bordered CustomResponsiveTable" id="PlayerTable">
    <thead>
        <tr>
            <th>Player Name</th>
            <th>Player Type</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerType)
                </td>
                <td>
                    @if (item.IsInCurrentTeam)
                    {
                        <span class="btn btn-danger btn-sm" onclick="RemoveFromTeam(@item.PlayerId, this)">Remove From Team</span>
                    }
                    else
                    {
                        <span class="btn btn-primary btn-sm" onclick="AddToTeam(@item.PlayerId, this)">Add to Team</span>
                    }
                </td>
            </tr>

        }

    </tbody>
</table>

<script>
    $(document).ready(function () {
        InitializeTable('PlayerTable');
    });
</script>