CricketFantasy/CricketFantasy/Controllers/TeamController.cs
using CricketFantasy.DataLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CricketFantasy.DataTransferObjects.Models;
using CricketFantasy.DataLayer.Model;

namespace CricketFantasy.Controllers
{
    public class TeamController : Controller
    {
        // GET: Team
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TeamManagement()
        {
            return View();
        }

         public ActionResult VirtualTeamManagement()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult ExistingTeam(string TeamName, int TeamId)
        {
            if(TeamId == 0)
            {
                return Json(!DataAccess.Instance.TeamAction.GetAll().Where(x => x.TeamName == TeamName).Any(), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(!DataAccess.Instance.TeamAction.GetAll().Where(x => x.TeamName == TeamName && x.Id != TeamId).Any(), JsonRequestBehavior.AllowGet);
            }

        }


        public PartialViewResult GetTeamData()
        {
            var d = DataAccess.Instance.TeamAction.GetAll().Where(x=>x.IsActive != false && x.IsVirtualTeam != true).AsEnumerable().Select(x => new TeamDTO
            {
                TeamId = x.Id,
                TeamName = x.TeamName,
                Country = x.country,
                PlayersCount = DataAccess.Instance.TeamPlayerAction.GetAll().Where(y => y.TeamId == x.Id).Count(),
            }).ToList();
            return PartialView(d);
        }
        
        public PartialViewResult GetVirtualTeamData()
        {
            var d = DataAccess.Instance.TeamAction.GetAll().Where(x=>x.IsActive == true && x.IsVirtualTeam == true).AsEnumerable().Select(x => new TeamDTO
            {
                TeamId = x.Id,
                TeamName = x.TeamName,
                Country = x.country,
                PlayersCount = DataAccess.Instance.TeamPlayerAction.GetAll().Where(y => y.TeamId == x.Id).Count(),
            }).ToList();
            return PartialView(d);
        }

        public PartialViewResult CreateTeam(int TeamId)
        {
            CreateTeamDto model = new CreateTeamDto();
            
            if (TeamId != 0)
            {
                var TeamInfo = DataAccess.Instance.TeamAction.Get(TeamId);
                model.TeamId = (int)TeamId;
                model.TeamName = TeamInfo.TeamName;
                model.CountryName = TeamInfo.country;
            }
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult CreateTeam(CreateTeamDto TeamData)
        {
            CreateTeamDto model = new CreateTeamDto();

            if (TeamData.TeamId != 0)
            {
                Team teaminfo = DataAccess.Instance.TeamAction.Get(TeamData.TeamId);
                teaminfo.TeamName = TeamData.TeamName;
                teaminfo.country = TeamData.CountryName;
                DataAccess.Instance.TeamAction.Change(teaminfo);
            }
            else
            {
                Team teaminfo = new Team();
                teaminfo.TeamName = TeamData.TeamName;
                teaminfo.country = TeamData.CountryName;
                teaminfo.IsActive = true;
                teaminfo.CreateUser = "0";
                teaminfo.CreateDate = DateTime.Now;
                DataAccess.Instance.TeamAction.Add(teaminfo);
                TeamData.TeamId = teaminfo.Id;
            }
            return Json(new { TeamId = TeamData.TeamId }, JsonRequestBehavior.AllowGet);
        }

    }
}

CricketFantasy/CricketFantasy/Views/Team/CreateTeam.cshtml
@model CricketFantasy.DataTransferObjects.Models.CreateTeamDto

@using (Ajax.BeginForm("CreateTeam", "Team", new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "CreateTeamSuccess",
    OnFailure = "CreateTeamFailure",
}))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TeamId)

        <div class="form-group">
            @Html.Label("Team Name", htmlAttributes: new { @class = "control-label col-md-3 requiredfield" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.TeamName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeamName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Country Name", htmlAttributes: new { @class = "control-label col-md-3 requiredfield" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-12 form-group">
            <a class="btn btn-primary" href="/Home/Players" target="_blank"> Add Players </a>
        </div>

        <div class="col-md-12" id="PlayersContainerDiv">
          
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" id="CreateTeamsBtn" class="HideItem btn btn-default" />
            </div>
        </div>
    </div>

}
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script>
    $(document).ready(function () {
        GetPlayersData();
    });
</script>

CricketFantasy/CricketFantasy/Views/Team/GetTeamData.cshtml
@model IEnumerable<CricketFantasy.DataTransferObjects.Models.TeamDTO>

<table class="table table-striped table-bordered CustomResponsiveTable" id="TeamTable">
    <thead>
        <tr>
            <th>
                Team Name    
            </th>
            <th>
                Total Players in Team
            </th>
            <th>
                View Players
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TeamName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayersCount)
                </td>
                <td>
                    <a href="#" onclick="ViewTeamPlayers(@item.TeamId)">View Players</a>
                </td>
                <td>
                    <span class="fa fa-pencil fontawesomeThemeColor EditAccount CursorClass" onclick="GetTeamModel('@item.TeamId')" title="Edit Team"></span> |
                     <span class="fa fa-trash fontawesomeThemeColor DeleteAccount CursorClass" onclick="DeleteTeam('@item.TeamId')" title="Delete Team"></span>
                </td>
            </tr>

        }

    </tbody>
</table>

<script>
    $(document).ready(function () {
        InitializeTable('TeamTable');
    });
</script>

CricketFantasy/CricketFantasy/Views/Team/GetVirtualTeamData.cshtml
@model IEnumerable<CricketFantasy.DataTransferObjects.Models.TeamDTO>

<table class="table table-striped table-bordered CustomResponsiveTable" id="VirtualTeamTable">
    <thead>
        <tr>
            <th>
                Team Name    
            </th>
            <th>
                Total Players in Team
            </th>
            <th>
                View Players
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TeamName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayersCount)
                </td>
                <td>
                    <a href="#" onclick="ViewVirtualTeamPlayers(@item.TeamId)">View Players</a>
                </td>
                <td>
                     <span class="fa fa-trash fontawesomeThemeColor DeleteAccount CursorClass" onclick="DeleteTeam('@item.TeamId')" title="Delete Team"></span>
                </td>
            </tr>

        }

    </tbody>
</table>

<script>
    $(document).ready(function () {
        InitializeTable('VirtualTeamTable');
    });
</script>

CricketFantasy/CricketFantasy/Views/Team/TeamManagement.cshtml
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">Team Management</h3>
        </div>
    </div>
</div>

<!-- END: Subheader -->
<div class="m-content">
    <div class="MainBody">
        <div class="col-md-12 form-group">
            <button class="btn btn-primary" onclick="GetTeamModel('0')"> Add/Create Team</button>
        </div>
        <div class="col-md-12 form-group" id="MainTeamDiv">

        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        GetTeamData();
    });
</script>

CricketFantasy/CricketFantasy/Views/Team/VirtualTeamManagement.cshtml
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title ">Virtual Team Management</h3>
        </div>
    </div>
</div>

<!-- END: Subheader -->
<div class="m-content">
    <div class="MainBody">
        <div class="col-md-12 form-group" style="display:none;">
            <button class="btn btn-primary" onclick="GetTeamModel('0')"> Add/Create Team</button>
        </div>
        <div class="col-md-12 form-group" id="MainVirutalTeamDiv">

        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        GetVirutalTeamData();
    });
</script>